portfolio/pjt/accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings


app_name = 'accounts'

urlpatterns = [
    path('', views.index,name='index'),
    path('signup/', views.signup,name='signup'),
    path('login/', views.login,name='login'),
    path('logout/', views.logout,name='logout'),
    path('user_list/',views.user_list,name='user_list'),
    path('delete/<int:pk>', views.delete ,name='delete'),
#   path('<int:user_pk>', views.profile ,name='profile'),
    path('profile/<username>', views.profile ,name='profile'),
    path('edit_profile/', views.edit_profile ,name='edit_profile'), 
    path('change_password/', views.change_password,name='change_password'),
    path('password/', views.password,name='password'),
#    path('my_profile/', views.my_profile ,name='my_profile'),
#    path('my_profile/edit/', views.edit_profile ,name='edit_profile'),
] 

portfolio/pjt/apps/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "apps"


urlpatterns = [
    path('', views.index,name="index"),
    path('count_length/',views.count_length,name='count_length'),
    path('lotto/', views.lotto,name="lotto"),
    path('practice/', views.practice,name="practice"),
    path('email_authentication/',views.email_authentication,name="email_authentication"),
    path('image_practice/', views.image_practice,name="image_practice"),
    path('carousel/',views.carousel,name='carousel'),
    path('drag_and_drop',views.drag_and_drop,name='drag_and_drop'),
    path('sticky_note',views.sticky_note,name='sticky_note'),
    path('create_note',views.create_note,name='create_note'),
    path('update_note/<int:pk>',views.update_note,name='update_note'),
    path('delete_note/<int:pk>',views.delete_note,name='delete_note'),

]

portfolio/pjt/pjt/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('photos/', include('photos.urls')),
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/pjt/accounts/models.py
import os
from django.db import models
from django.contrib.auth.models import AbstractUser	# AbstractUser 불러오기



class User(AbstractUser):
    profile_name = models.CharField(max_length=100)
    profile_image = models.ImageField(upload_to="image/profile_image", blank=True )

  
            
            

portfolio/pjt/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm , UserChangeForm
from .models import User
from django.contrib.auth import get_user_model

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ["username", "password1", "password2", "email", 'first_name', 'last_name']
        
        labels = {
        "username" : "아이디", 
        "password1":"비밀번호", 
        "password2":"비밀번호 확인", 
        "email":"이메일", 
        'first_name':"성", 
        'last_name':"이름",
        "profile_image":"프로필 사진",
      }
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].help_text = None
        self.fields['password2'].help_text = None
        self.fields['username'].help_text = None
    
        

class CustomUserChangeForm(UserChangeForm):
      class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']

portfolio/pjt/accounts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from .forms import UserForm
from .forms import CustomUserChangeForm
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import check_password

from django.http import HttpResponse
import os
from photos.models import photo
import smtplib
from email.mime.text import MIMEText
import shutil


# Create your views here.

def index(request):
    
    
    return render(request,'accounts/index.html')


def find_password(request,stage):
    
    print(stage)
    
    return render(request,'accounts/find_password.html')

@csrf_exempt
def login(request):
  
  if request.user.is_authenticated:
    
    return redirect('photos:index')

  else:

    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'photos:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('accounts:login') 
    
@csrf_exempt
def signup(request):
  
    if  request.user.is_authenticated:
       return redirect('photos:index')
    else:
        if request.method == 'POST':
            
            form = UserForm(request.POST)
            # 유효성 검사
            if form.is_valid():
                user = form.save()
                # 회원가입 후 로그인 상태로 만들어줌
                return redirect('accounts:login')
        else:
            form = UserForm()

        context = {
            'form' : form,
        }
        
        return render(request, 'accounts/signup.html', context)

def user_list(request):
    
    users = get_user_model().objects.all()
    
    context ={
        
        'users' : users,
        
    }
    
    return render(request,'accounts/user_list.html',context)

def delete(request,pk): 
    
  user = get_user_model().objects.get(pk=pk).delete()

  return redirect('accounts:user_list')

  
def profile(request,username):
  
    User =  get_user_model().objects.get(username = username)
    
    context ={
      
      'User': User,
          
    }
    
    return render(request,'accounts/profile.html',context)
        
  

@login_required
def edit_profile(request):

      if request.method == 'POST':
          form = CustomUserChangeForm(request.POST ,instance=request.user)
          if form.is_valid():
              user = form.save()  
              try:
                user.profile_image =request.FILES['image']
                user.save()
              except:
                print('error')


              return redirect('photos:index')
      else:
          form = CustomUserChangeForm(instance=request.user)
      
      context = {
          'form': form,
      }

      return render(request,'accounts/edit_profile.html',context)




@csrf_exempt

def change_password(request):
    context= {}
    if  request.user.is_authenticated:
        if request.method == "POST":
            current_password = request.POST.get("origin_password")
            user = request.user
            if check_password(current_password,user.password):
                new_password = request.POST.get("password1")
                password_confirm = request.POST.get("password2")
                if new_password == password_confirm:
                    user.set_password(new_password)
                    user.save()
                    return redirect("photos:index")
                else:
                    context.update({'error':"새로운 비밀번호를 다시 확인해주세요."})
        else:
            context.update({'error':"현재 비밀번호가 일치하지 않습니다."})

        return render(request, "accounts/change_password.html",context)
    else:
        return redirect('photos:index')
    

def password(request):



    return redirect('accounts:change_password')
    
    

portfolio/pjt/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}회원가입{% endblock title %}


{% block content %}
   
<div class="container" style="background-color: yellow; display: flex; justify-content: center; align-items: center;">
  <div class="login_container">
      <div class="login_title" style="margin: 20px;">
          Change Password
      </div>
      <form method="POST" action="{% url 'accounts:change_password' %}" class="login_form">
          {% csrf_token %}

          <div class="login_input_container" style = 'margin-bottom: 20px;'>
              <div class="username_form_text">Origin Password</div>
              <div class="input_container">
                  <input class="login_input" name="origin_password" type="password">
              </div>

              <div class="password_form_text"> New Password</div>
              <div class="input_container">
                  <input class="login_input" name="password1" type="password">
              </div>
              <div class="confirm_password_form_text">Confirm Password</div>
              <div class="input_container">
                  <input class="login_input" name="password2" type="password">
              </div>
          </div>
          <input type="submit" class="login_btn" sytle="margin:100px;" value="Submit">
  </div>
  </form>
</div>

{% endblock content %}

portfolio/pjt/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}회원가입{% endblock title %}

{% block content %}

<div class="container d-flex flex-column align-items-center col-auto" style="margin-bottom:50px width:300px;">


    <h1 style ='font-size: 30px; margin-top:20px;'>{{user}} 프로필</h1>

    <div class="container"></div>


    <form  action="" method="POST" method="POST" enctype="multipart/form-data">

        <div class = 'd-flex flex-column justify-content-center align-items-center ' style = 'margin-top: 20px;'>
            <label for="input-image">
                {% if user.profile_image %}       
                    <img style="border-radius: 10px; width:300px; height:300px;margin:5px;" id="preview-image" src="{{ user.profile_image.url }}">
                {% else %}
                    <img style="border-radius: 10px; width:300px; height:300px;margin:5px;" id="preview-image" src="https://dummyimage.com/200x200/000/fff">
                {% endif %}
            
            </label>
            <input style="display: none;" type="file" id="input-image" name="image" accept=".gif, .jpg, .png">
            <p style="color:red;font-size:10px;">이미지는 *.gif, *.jpg, *.png 형식만 가능합니다. </p>
        </div>
        
        {% csrf_token %}
        {% bootstrap_form form %}
        {% comment %} <a href = "{% url 'accounts:change_password'%}" >비밀번호 변경</a> {% endcomment %}

        <div class = "d-flex justify-content-center margint-top:5px; ">
            <button class = 'btn btn-outline-primary' style = "margin:5px;"  type="submit">수정</button>
            <a href="{% url 'accounts:index' %}">
                <button class='btn btn-outline-danger' style = "margin:5px;" type="button" >취소</button>
            </a>
        </div>
    </form>



</div>

<script>
    function readImage(input) {
        // 인풋 태그에 파일이 있는 경우
      if(input.files && input.files[0]) {
          // 이미지 파일인지 검사 (생략)
          // FileReader 인스턴스 생성
          const reader = new FileReader()
          // 이미지가 로드가 된 경우
          reader.onload = e => {
              const previewImage = document.getElementById("preview-image")
              previewImage.src = e.target.result
            }
          // reader가 이미지 읽도록 하기
          reader.readAsDataURL(input.files[0])
      }
  }
  // input file에 change 이벤트 부여
  const inputImage = document.getElementById("input-image")
  inputImage.addEventListener("change", e => {
      readImage(e.target)
  })

  </script>


{% endblock content %}

portfolio/pjt/templates/accounts/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
 
<div style = 'display: flex;'>
    <a href="{% url 'apps:index' %}">
        <div style="background-color: black; width: 250px; margin: 20px; border-radius: 20px;">
            a
        </div>
    </a>
    
</div>



{% endblock %}

portfolio/pjt/templates/accounts/login.html
{% extends 'base.html' %}

{% load static %}

{% load bootstrap4 %}

{% block content %}

<div class="container  d-flex flex-column align-items-center" style = 'margin-top: 100px;'>

    <h1>로그인</h1>

    <div class = 'container d-flex justify-content-center align-items-center'>
        <div class="login_container" style='margin-right:10px;'>
           
            <form action="" style="margin-top:10px;" class="d-flex flex-column" method="POST">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input class='btn btn-outline-primary' type="submit" value="로그인">
            </form>
            <a style="margin-top:2rem;"  href ="#" > 비밀번호를 잊으셨나요? </a>
        </div>
        <img src="{% static 'img/바다사진.jpg' %}" style='width:200px; height:200px; border-radius:20px;'>
        {% comment %} <div class="video_container" style='width:50px; height:50px;'>
        
        </div> {% endcomment %}


    </div>
</div>

{% endblock %}

portfolio/pjt/templates/accounts/profile.html
{% extends 'base.html' %}

{% load static %}

{% load bootstrap4 %}

{% block title %}{{user}}님 의 프로필 정보{% endblock title %}

{% block content %}

    <h1 style = 'margin-top: 150px;'>{{ User }} 프로필</h1>
    <div class="d-flex justify-content-center align-items-center">
        <div class="d-flex align-items-center" style="margin:50px;">
            <div style="width:300; height:300px; padding:30px; margin:10px;">
                {% if User.profile_image  %}
                <div style="width: 200px; height:200px; overflow: hidden;" >
                    <img src="{{User.profile_image.url}}" class="card-img-top"  style="width:100%; height:100%; object-fit: cover;" alt="" >
                </div>
                {% else %}
                    <img src="https://dummyimage.com/200x200/000/fff" class="card-img-top" style="width:100%; height:100%;" alt="">
                {% endif %}
            </div>
    
            <div sytle="margin:0px;" style="width:300px;">
                <p> {{ User.last_name }}{{ User.first_name }} </p>
                <p> {{ User.email }} </p>
                {% if user == User %}
                    <a href="{% url 'accounts:edit_profile' %}">프로필 편집</a>
                {% endif %}
            </div> 
    
        </div>
    
    </div>
    


{% endblock content %}

portfolio/pjt/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}회원가입{% endblock title %}


{% block content %}
<div class="container" style="display: flex; justify-content: center; align-items: center;margin-top: 100px;" >

    <section class="container d-flex flex-column justify-content-center align-items-center" >
        <h1>회원가입</h1>
        
        <form method="POST" action="{% url 'accounts:signup' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-primary col-12" value="제출" style="width: 300px;">
        </form>

    </section>
</div>
<script>
    function readURL(input) {
    alert(1);
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function(e) {
        document.getElementById('display-image').src = e.target.result;
        };
        reader.readAsDataURL(input.files[0]);
    } else {
        document.getElementById('display-image').src = "";
    }
    }
</script>

{% endblock content %}

portfolio/pjt/templates/accounts/user_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}회원가입{% endblock title %}



<table>
    <tr>
      <th scope="col">User ID</td>
      <th scope="col">User Name</td>
      <th scope="col">User Email</td>
      <th scope="col">Delete</td>
    </tr>
    <tr>
      <td>11/15</td>
      <td>김우직</td>
      <td>남</td>
    </tr>
    
  </table>


{% block content %}

<table style = 'margin-top: 100px; margin-left: 30px; '>
    <tr>
      <th scope="col">User ID</td>
      <th scope="col">User Name</td>
      <th scope="col">User Email</td>
      <th scope="col">Delete</td>
    </tr>
    {% for user in users %}
    <tr>
      <td>{{ user.id }}</td>
      <td>{{user.username}}</td>
      <td>{{user.email}}</td>
      <td><a href="{% url 'accounts:delete' user.pk %}">del</a></td>
    </tr>
    {% endfor %}

  </table>

    
{% endblock content %}