portfolio/pjt/accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings


app_name = 'accounts'

urlpatterns = [
    path('', views.index,name='index'),
    path('signup/', views.signup,name='signup'),
    path('login/', views.login,name='login'),
    path('logout/', views.logout,name='logout'),
    path('user_list/',views.user_list,name='user_list'),
    path('delete/<int:pk>', views.delete ,name='delete'),
#   path('<int:user_pk>', views.profile ,name='profile'),
    path('profile/<username>', views.profile ,name='profile'),
    path('edit_profile/', views.edit_profile ,name='edit_profile'), 
    path('change_password/', views.change_password,name='change_password'),
    path('password/', views.password,name='password'),
#    path('my_profile/', views.my_profile ,name='my_profile'),
#    path('my_profile/edit/', views.edit_profile ,name='edit_profile'),
] 

portfolio/pjt/apps/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "apps"


urlpatterns = [
    path('', views.index,name="index"),
    path('count_length/',views.count_length,name='count_length'),
    path('lotto/', views.lotto,name="lotto"),
    path('practice/', views.practice,name="practice"),
    path('email_authentication/',views.email_authentication,name="email_authentication"),
    path('image_practice/', views.image_practice,name="image_practice"),
    path('carousel/',views.carousel,name='carousel'),
    path('drag_and_drop',views.drag_and_drop,name='drag_and_drop'),
    path('sticky_note',views.sticky_note,name='sticky_note'),
    path('create_note',views.create_note,name='create_note'),
    path('update_note/<int:pk>',views.update_note,name='update_note'),
    path('delete_note/<int:pk>',views.delete_note,name='delete_note'),

]

portfolio/pjt/photos/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "photos"


urlpatterns = [
    path('', views.index,name="index"),
    path('second_index', views.second_index,name="second_index"),
    path('PhotoUpload/', views.PhotoUpload, name="PhotoUpload"),
    path('PhotoUpdate/<int:photo_pk>', views.PhotoUpdate, name="PhotoUpdate"),
    path('display_image/', views.display_image, name="display_image"),
    path('detail/<int:pk>', views.detail ,name='detail'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:photo_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:photo_pk>/likes/', views.likes, name='likes'),

]

portfolio/pjt/pjt/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('photos/', include('photos.urls')),
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/pjt/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Document</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    
    {% block style %}
    {% endblock %}
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'photos:index' %}"><img  src="{% static 'img/Photos-logo-black.png' %}" style="width: 50px; height: 50px;" alt=""></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'apps:sticky_note' %}">sticky_note <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'photos:index' %}">photos <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'apps:index' %}">apps</a>
                    </li>
                    
                </ul>
                {% if user.is_authenticated %}
                    <a href="{% url 'accounts:profile' user.username  %}">
                        <div style="margin:6px; margin-right: 10px;" >{{ user.username }}</div>
                    </a>
                    <a href="{% url 'accounts:logout' %}">Logout</a>     
                {% else %}
                    <a href="{% url 'accounts:login' %}"><div style="margin:6px; margin-right: 10px;">Login</div></a>    
                    <a href="{% url 'accounts:signup' %}">Signup</a>
                {% endif %}
            </div>
        </nav>
    </header>
    <main style="margin-top: 60px; " >
        {% block content %}
        
        {% endblock %}  
    </main>
    <footer>




    </footer>
    <script src="{% static 'js/func.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</body>
</html>