portfolio/pjt/accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings


app_name = 'accounts'

urlpatterns = [
    path('', views.index,name='index'),
    path('signup/', views.signup,name='signup'),
    path('login/', views.login,name='login'),
    path('logout/', views.logout,name='logout'),
    path('user_list/',views.user_list,name='user_list'),
    path('delete/<int:pk>', views.delete ,name='delete'),
#   path('<int:user_pk>', views.profile ,name='profile'),
    path('profile/<username>', views.profile ,name='profile'),
    path('edit_profile/', views.edit_profile ,name='edit_profile'), 
    path('change_password/', views.change_password,name='change_password'),
    path('password/', views.password,name='password'),
#    path('my_profile/', views.my_profile ,name='my_profile'),
#    path('my_profile/edit/', views.edit_profile ,name='edit_profile'),
] 

portfolio/pjt/apps/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "apps"


urlpatterns = [
    path('', views.index,name="index"),
    path('count_length/',views.count_length,name='count_length'),
    path('lotto/', views.lotto,name="lotto"),
    path('practice/', views.practice,name="practice"),
    path('email_authentication/',views.email_authentication,name="email_authentication"),
    path('image_practice/', views.image_practice,name="image_practice"),
    path('carousel/',views.carousel,name='carousel'),
    path('drag_and_drop',views.drag_and_drop,name='drag_and_drop'),
    path('sticky_note',views.sticky_note,name='sticky_note'),
    path('create_note',views.create_note,name='create_note'),
    path('update_note/<int:pk>',views.update_note,name='update_note'),
    path('delete_note/<int:pk>',views.delete_note,name='delete_note'),

]

portfolio/pjt/photos/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "photos"


urlpatterns = [
    path('', views.index,name="index"),
    path('second_index', views.second_index,name="second_index"),
    path('PhotoUpload/', views.PhotoUpload, name="PhotoUpload"),
    path('PhotoUpdate/<int:photo_pk>', views.PhotoUpdate, name="PhotoUpdate"),
    path('display_image/', views.display_image, name="display_image"),
    path('detail/<int:pk>', views.detail ,name='detail'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:photo_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:photo_pk>/likes/', views.likes, name='likes'),

]

portfolio/pjt/pjt/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('photos/', include('photos.urls')),
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/pjt/templates/apps/code.html
{% extends 'base.html' %}
{% block content %}


  <div class="container" style="margin-top: 100px;">
    <h1 style = 'margin-bottom: 50px;'>
      {{ email }}
    </h1>
    <form action="" method="post" class="form-example" style="margin-left: 400px;">
      <div style="display: flex;">
        <div class="form-example">
          <label for="code">Enter code: </label>
          <input type="text" name="code" id="code" required />
        </div>
        <button type="button" class="btn btn-outline-primary" onclick="check_code()" >확인</button>
      </div>
      
    </form>
  </div>


      <script>

        function check_code(){
            
            code = document.getElementById('code').value;


            if(code == {{ code }}  ){
                
                alert('ok');
                window.location.href="{% url 'photos:index' %}";
            }
            else{
                alert('not ok');
            }
                

        }
        

        $('#submit').click(check_code);


      </script>

{% endblock %}

portfolio/pjt/templates/apps/count_length.html
{% extends 'base.html' %}
{% block content %}

  <div class="container">
    <h1 style="margin-top:100px;">자기소개서 글자수 세기</h1>
    <textarea name="" style="width:1100px; height:800px ;" id="input-sentence" onkeyup="A()" ></textarea>
    <div style="display: flex;  margin-top: 10px; "><p style="font-size: 30px; margin-right: 10px;">공백 포함 :<p id="count-length" style="font-size: 30px;" >0</p><p style="font-size: 30px;">글자</p></div>
    <div style="display: flex;  margin-top: 10px; "><p style="font-size: 30px; margin-right: 10px;">공백 제외 : </p><p id="count-replaced" style="font-size: 30px;" >0</p><p style="font-size: 30px;">글자</p></div>
  </div>
  <script>
    function A(){
        input = document.getElementById('input-sentence').value
        replaced_blank = input.replaceAll(' ','')
        count_replaced = document.getElementById('count-replaced')
        count = document.getElementById('count-length')
        count.innerText = input.length
        count_replaced.innerText = replaced_blank.length


    }
    



  </script>
{% endblock %}

portfolio/pjt/templates/apps/drag_and_drop.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- index.html -->
<!DOCTYPE html>
<html>
  <head>
    <link href="{% static 'css/common.css' %}" rel="stylesheet"/>
    <script src="{% static 'js/event_handler.js' %}"></script>
  </head>
  <body>
    <div class="ball green s200"></div>
    <div class="ball blue s100"></div>
    <div class="ball pink s50"></div>                                                                                                                                                                                                         
    <script src="{% static 'js/common.js' %}"></script>
  </body>
</html>


{% endblock %}

portfolio/pjt/templates/apps/email_authentication.html
{% extends 'base.html' %}
{% block content %}

  <div class="container" style="margin-top: 120px;" >
  <h1>이메일 인증</h1>
    <form action="" method="post" class="form-example"  >
      <div style="display:flex; margin-left: 350px; margin-top: 50px;">
        <div class="form-example">
          <label for="email">Enter your email: </label>
          <input type="email" name="email" id="email" required />
        </div>
        <div class="form-example">
          <input class="btn btn-outline-primary" type="submit" value="Send Email " />
        </div>
      </div>
    </form>
  </div>


{% endblock %}

portfolio/pjt/templates/apps/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div style="display:flex; justify-content: center; align-items: center; margin-top: 150px;">

    <div style = 'display:flex;'>
        <a href="{% url 'apps:lotto' %}">
            <div style="background-color: black; border-style:solid; border-color:black; width: 300px; height: 300px; margin: 20px; border-radius: 20px; overflow: hidden;">
                <img src="{% static 'img/lotto.jpg'  %}" alt="" style="width:300px; height: 300px;">
            </div>
        </a>
        <a href="{% url 'apps:email_authentication' %}">
            <div style="background-color: black; border-style:solid; border-color:black; width: 300px; height: 300px; margin: 20px; border-radius: 20px; overflow: hidden;">
                <img src="{% static 'img/mail.png'  %}" alt="" style="width:300px; height: 300px;">
            </div>
        </a>
        <a href="{% url 'apps:count_length' %}">
            <div style="background-color: black; border-style:solid; border-color:black; width: 300px; height: 300px; margin: 20px; border-radius: 20px; overflow: hidden;">
                <img src="{% static 'img/character_counter.png'  %}" alt="" style="width:300px; height: 300px;">
            </div>
        </a>
    </div>
    
</div>


{% endblock %}

portfolio/pjt/templates/apps/lotto.html
{% extends 'base.html' %}
{% block content %}

<div style="margin-top: 100px;">
    <h1>로또 번호 생성기</h1>
    <div class="inner">

        <div id="lotto1" style="display:flex; justify-content: center; align-items: center; height: 100px; width: 100px; background-color: grey; margin: 10px; border-width: 1px; border-radius: 50%;">
            L
        </div>
        <div id="lotto2" style="display:flex; justify-content: center; align-items: center; height: 100px; width: 100px; background-color: grey; margin: 10px; border-width: 1px; border-radius: 50%;">
            o
        </div>
        <div id="lotto3" style="display:flex; justify-content: center; align-items: center; height: 100px; width: 100px; background-color:  grey; margin: 10px; border-width: 1px; border-radius: 50%;">
            T
        </div>
        <div id="lotto4" style="display:flex; justify-content: center; align-items: center; height: 100px; width: 100px; background-color: grey; margin: 10px; border-width: 1px; border-radius: 50%;">
            T
        </div>
        <div id="lotto5" style=" display:flex; justify-content: center; align-items: center; height: 100px; width: 100px; background-color: grey; margin: 10px; border-width: 1px; border-radius: 50%;">
            o
        </div>
        <div id="lotto6" style="display:flex; justify-content: center; align-items: center; height: 100px; width: 100px; background-color: grey; margin: 10px; border-width: 1px; border-radius: 50%;">
            !
        </div>
        <button class="btn btn-outline-primary" style="width: 80px; height: 80px; border-radius: 10px; margin-top: 20px;"  onclick="ChangeNumber()">
            생성
        </button>

    </div>
    
</div>



{% endblock %}

portfolio/pjt/templates/apps/practice.html
{% extends 'base.html' %}
{% block content %}

<h1>자바스크립트 연습</h1>

<div class="border" style="justify-content: center; align-items: center;">

    <button onclick = "calc()" > 나이 계산하기 </button>
    <div id="result" style = 'margin:10px;'></div>



    <img id="practice-image" src="https://dummyimage.com/400x400/000/fff" alt="">
    <button  onclick="practice_image()"style='width:200px; height:50; border-radius:5px; margin:10px;'>btn</button>
    <p id = "practice-ptag" >practice ptag </p>
    <button  onclick="practice_ptag()"style='width:200px; height:50; border-radius:5px; margin:10px;'>btn</button>
    <div id="practice-div" style="background-color: black; width:500px; height: 500px; border-radius: 25px; margin:10px;"></div>
    <button  onclick="practice_div()"style='width:200px; height:50; border-radius:5px; margin:10px;'>btn</button>
    <button id='button1' style="margin:50px;" >button1</button>
    <button id='button2' style="margin:50px;" >button2</button>    
</div>




<script>

    function calc(){

        let currentYear = 2024;

        let age = currentYear - prompt('출생년도 입력') + 1

        document.getElementById('result').innerHTML = "나이는 "+ age +'세'; 
    }


    const button1 = document.querySelector('#button1');
    const button2 = document.querySelector('#button2');
    //1번
    const print = () => {
    	alert('button1');
    }
	button1.addEventListener('click', print);

    button2.addEventListener('click', () => {
   	    alert('button2');
   });


    function practice_ptag(){

    image = document.getElementById('practice-ptag');

    image.innerText = "변경됨";


    }

    function practice_div(){

    image = document.getElementById('practice-div');

    if(image.style.backgroundColor == "black")
        image.style.backgroundColor = 'gray';
    else
        image.style.backgroundColor = 'black';

    }

    function practice_image(){

    image = document.getElementById('practice-image');

    if(image.src == "https://dummyimage.com/400x400/0f0/00f")
        image.src = "https://dummyimage.com/400x400/000/fff";
    else
        image.src = "https://dummyimage.com/400x400/0f0/00f";

    }
</script>


{% endblock %}

portfolio/pjt/templates/apps/sticky_note.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
    <link href="{% static 'css/common.css' %}" rel="stylesheet"/>
    <script src="{% static 'js/event_handler.js' %}"></script>
    <style>
        .drag{

            background-color: red;

        }


    </style>

{% endblock %}
{% block content %}+
    <div class="container" style="margin-top: 100px;">
        <div class = 'display:flex;'>
            <button style = 'margin: 10px;' onclick="location.href='/apps/create_note'" >
                새 노트 생성
            </button>
        </div>
            <div id="container" draggable="true" style = 'position: absolute; display: flex; flex-wrap: wrap; width: 1200px; background-color: pink;'>
                {% if user.is_authenticated %}  
                {% for note in notes %}
                <div class="note"  style = 'margin: 10px; '>
                <form method="POST" action="{% url 'apps:update_note' note.id %}" enctype="multipart/form-data">{% csrf_token %}
                    
                        <div style="width: 240px; height: 40px; background-color:brown ; padding: 5px;" >
                            <div style="display:flex;" > 
                                <div style = 'width:200px;'>
                                    
                                </div>
                                <div style=" width: 30px;">
                                    <a  href="{% url 'apps:delete_note' note.id %}">
                                        <img src="https://cdn-icons-png.flaticon.com/512/1/1766.png" style ="width:30px; height:30px;" alt="">
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div  style="background-color: yellow; width: 240px; "><!--포스트잇 부분-->
                            <textarea  name="note" style="width: 200px; height:200px; margin:20px; background-color: yellow; border-color: yellow;" onchange="this.form.submit()">{{ note.content }}</textarea>
                        </div>
                    
                </form>
                </div>
                {% endfor %} 
                {% else %}
                <p><a href="{% url 'accounts:login' %}">로그인</a>이 필요합니다.</p>
                {% endif %}
            </div>
    </div>
    <script src="{% static 'js/common.js' %}"></script>
    <script>


    </script>

{% endblock %}