portfolio/pjt/accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings


app_name = 'accounts'

urlpatterns = [
    path('', views.index,name='index'),
    path('signup/', views.signup,name='signup'),
    path('login/', views.login,name='login'),
    path('logout/', views.logout,name='logout'),
    path('user_list/',views.user_list,name='user_list'),
    path('delete/<int:pk>', views.delete ,name='delete'),
#   path('<int:user_pk>', views.profile ,name='profile'),
    path('profile/<username>', views.profile ,name='profile'),
    path('edit_profile/', views.edit_profile ,name='edit_profile'), 
    path('change_password/', views.change_password,name='change_password'),
    path('password/', views.password,name='password'),
#    path('my_profile/', views.my_profile ,name='my_profile'),
#    path('my_profile/edit/', views.edit_profile ,name='edit_profile'),
] 

portfolio/pjt/photos/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "photos"


urlpatterns = [
    path('', views.index,name="index"),
    path('second_index', views.second_index,name="second_index"),
    path('PhotoUpload/', views.PhotoUpload, name="PhotoUpload"),
    path('PhotoUpdate/<int:photo_pk>', views.PhotoUpdate, name="PhotoUpdate"),
    path('display_image/', views.display_image, name="display_image"),
    path('detail/<int:pk>', views.detail ,name='detail'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:photo_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:photo_pk>/likes/', views.likes, name='likes'),

]

portfolio/pjt/pjt/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('photos/', include('photos.urls')),
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/pjt/photos/models.py
 
from django.db import models
from django.conf import settings
 
class photo(models.Model):
    title = models.TextField(max_length=40, null=True)
    imgfile = models.ImageField(null=True, upload_to="", blank=True)
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_photos')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title
    

class comment(models.Model):
    photo = models.ForeignKey(photo, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

portfolio/pjt/photos/forms.py
# fileupload/forms.py
from django.forms import ModelForm
from .models import photo,comment
from django.forms import ModelForm, TextInput, EmailInput, NumberInput,FileInput

class PhotoUploadForm(ModelForm):
    class Meta:
        model = photo
        fields = ['title', 'imgfile', 'content']

        widgets = {
            'title': TextInput(attrs={
                'class': "form-control",
                'style': 'width: 300px;',
                'placeholder': 'title'

                }),
            'imgfile': FileInput(attrs={
                'class': "form-control",
                'style': 'width: 300px;',
                'id':'image-file',
                 'onchange': "readURL(this);"
                }),
            'content': TextInput(attrs={
                'class': "form-control",
                'style': 'width: 300px; height:100px;',
                'placeholder': 'content',
            }),

        }

class CommentForm(ModelForm):

    class Meta:
        model = comment
        # fields = '__all__'
        exclude = ('photo', 'user',)

        widgets = {
            'content': TextInput(attrs={
                'class': "form-control",
                'style': 'width: 780px; height:200px; margin-bottom:10px;',
                'placeholder': 'content'

                }),
            

        }

class PhotoChangeForm(ModelForm):
    class Meta:
        model = photo
        fields = ['title', 'imgfile', 'content']

        widgets = {
            'title': TextInput(attrs={
                'class': "form-control",
                'style': 'width: 300px; height:100px;',
                'placeholder': 'title'

                }),
            'imgfile': FileInput(attrs={
                'class': "form-control",
                'style': 'width: 300px; ',
                'id':'image-file',
                 'onchange': "readURL(this);"
                }),
            'content': TextInput(attrs={
                'class': "form-control",
                'style': 'width: 300px; height:100px;',
                'placeholder': 'content',
            }),

        }

portfolio/pjt/photos/views.py
from django.shortcuts import render ,redirect
from django.views.decorators.http import require_GET, require_POST
from django.views.decorators.csrf import csrf_exempt
from .forms import PhotoUploadForm,CommentForm,PhotoChangeForm
from .models import photo,comment

# Create your views here.

import random


def index(request):
    images = photo.objects.all().order_by('-id')
    ordered_images = photo.objects.all().order_by('-like_users') 



    context = {
            'A': 'A',
            'images' : images,
            'ordered_images' : ordered_images,
    }

    return render(request, 'photos/index.html', context)

def second_index(request):
    images = photo.objects.all() 



    context = {
            'A': 'A',
            'images' : images
    }

    return render(request, 'photos/display_image.html', context)






def PhotoUpload(request):
    
    if request.user.is_authenticated:
        
        if request.method == 'POST':
            title = request.POST['title']
            content = request.POST['content']
            img = request.FILES["imgfile"]

            photos = photo.objects.create(title=title,content=content,imgfile=img,user=request.user)
            photos.save()
            return redirect('photos:index')
        else:
            Form = PhotoUploadForm()
            context = {
                'Form': Form ,
            }
            return render(request, 'photos/PhotoUpload.html', context)
    else:
        return redirect('accounts:login')


    
def display_image(request):

    images = photo.objects.all() 



    context = {
            'A': 'A',
            'images' : images
    }

    return render(request, 'photos/display_image.html', context)





def detail(request,pk):

    _photo =photo.objects.get(id=pk)
    
    comments = comment.objects.filter(photo=_photo)
    comment_form = CommentForm()
    likes =_photo.like_users.all()
            
    context={
        
        'photo':_photo,
        'comment_form':comment_form,
        'comments' : comments,
        'likes':likes,


    }



    return render(request,'photos/detail.html',context)

def comments_create(request, pk):
    if request.user.is_authenticated:
        _photo = photo.objects.get(id=pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            _comment = comment_form.save(commit=False)
            _comment.photo = _photo
            _comment.user = request.user
            _comment.save()
        return redirect('photos:detail', pk)
    return redirect('accounts:login')



def comments_delete(request, photo_pk, comment_pk):
    if request.user.is_authenticated:
        _comment = comment.objects.get(id = comment_pk)
        if request.user == _comment.user:
            _comment.delete()
    return redirect('photos:detail', photo_pk)

@csrf_exempt
@require_POST
def likes(request, photo_pk):
    if request.user.is_authenticated:
        _photo = photo.objects.get(id=photo_pk)

        if _photo.like_users.filter(pk=request.user.pk).exists():
            _photo.like_users.remove(request.user)
        else:
            _photo.like_users.add(request.user)
        return redirect('photos:index')
    return redirect('accounts:login')

@csrf_exempt
def PhotoUpdate(request,photo_pk):
    
    if request.user:
        
        _photo = photo.objects.get(id=photo_pk)

        if request.method == 'POST':
            _photo.title = request.POST['title']
            _photo.content = request.POST['content']
            
            try:
                _photo.imgfile = request.FILES["imgfile"]
            except:
                pass
            
            _photo.save()
            
            return redirect('photos:index')
        else:
            Form = PhotoChangeForm( instance = _photo)
            
            context = {
                'Form': Form ,
                'photo': _photo,
            }
            return render(request, 'photos/PhotoUpdate.html', context)
    else:
        return redirect('accounts:login')

portfolio/pjt/templates/photos/PhotoUpdate.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}

<div style="margin-top:100px;">

    <h1>사진 업데이트</h1>
    <div class="container" style="display: flex; justify-content: center; align-items: center; ">
        
        <div>
            
            <div style="height: 300px; width: 300px; overflow:hidden; margin: 10px;">
                    <img id="display_image" src={{ photo.imgfile.url}} alt="" style=" width:100%; height:100%; object-fit:cover; border-radius: 20px;">
            </div>

            <form method="POST" action="{% url 'photos:PhotoUpdate' photo.id %}" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="border">
                    <label for="imgfile" style ='text-align: left;'>Image File</label>
                    <input type="FILE" name = imgfile onchange="readURL(this)" style='margin-bottom:5px;'>
                    <label for="title" style ='text-align: left;' >Title</label>
                    <input type="text" name ='title' value = {{photo.title}} style ='width: 300px;'>
                    <label for="content" style ='text-align: left;' style='margin-bottom:5px;'>Content</label>
                    <input type="text" name ='content'value = {{photo.content}} style='margin-bottom:5px; width: 300px; height: 100px;'>
                    <input type="submit" class="btn btn-primary col-12" value="제출" style="width: 300px;">
                </div>
                
            </form>
        </div>
    </div>
</div>
    
<script>
    function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function(e) {
        document.getElementById('display_image').src = e.target.result;
        };
        reader.readAsDataURL(input.files[0]);
    } else {
        document.getElementById('display_image').src = "";
    }
    }
</script>
{% endblock%}

portfolio/pjt/templates/photos/PhotoUpload.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}

<div style="margin-top:100px;">

    <h1>사진 업로드</h1>
    <div class="container" style="display: flex; justify-content: center; align-items: center; ">
        
        <div>
            <div style="height: 300px; width: 300px; overflow:hidden; margin: 10px;">
                <img id="display_image" src="https://dummyimage.com/300x300/000/fff" alt="" style=" width:100%; height:100%; object-fit:cover; border-radius: 20px;">
            </div>
            <form method="POST" action="{% url 'photos:PhotoUpload' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form Form %}
                <input type="submit" class="btn btn-primary col-12" value="제출" style="width: 300px;">
            </form>
        </div>
    </div>
</div>
    
<script>
    function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function(e) {
        document.getElementById('display_image').src = e.target.result;
        };
        reader.readAsDataURL(input.files[0]);
    } else {
        document.getElementById('display_image').src = "";
    }
    }
</script>
{% endblock%}

portfolio/pjt/templates/photos/code.html
{% extends 'base.html' %}
{% block content %}
<p>{{ email }}</p>
    <form action="" method="post" class="form-example">
        <div class="form-example">
          <label for="code">Enter code: </label>
          <input type="text" name="code" id="code" required />
        </div>
        <div class="form-example">
          <input id="submit" value="Subscribe!" onclick="check_code()"/>
        </div>
      </form>

      <script>

        function check_code(){
            
            code = document.getElementById('code').value;


            if(code == {{ code }}  ){
                
                alert('ok');
                window.location.href="{% url 'photos:index' %}";
            }
            else{
                alert('not ok');
            }
                

        }
        

        $('#submit').click(check_code);


      </script>

{% endblock %}

portfolio/pjt/templates/photos/detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="container" style="margin-top: 100px; width: 800px;">
        {% if request.user == photo.user %}
        <a href="{% url 'photos:PhotoUpdate' photo.id %}">
            <button>
                수정
            </button>
        </a>
        {% endif %}
        <div style="display: flex; justify-content: center; align-items: center;">
            <p style ='font-size: 30px;'>{{photo.title}}</p>
        </div>
        <hr>
        <div style="display: flex; justify-content: center; align-items: center; width: 780px; height: 780px;">
            <img src="{{photo.imgfile.url}}" style="object-fit: cover; width: 780px; height: 780px; border-radius: 40px;" alt="">
        </div>
        <hr>
        <div style=" width: 700px; height: 300px; margin-left: 50px;">
            <p style>{{photo.content}}</p>
        </div>
        <hr>
        <h4>댓글 목록</h4>
        <hr>
<!--read-->
        {% if comments %}
        <p><b>{{ comments|length }}개의 댓글이 있습니다.</b></p>
        {% endif %}
        <ul>
        {% for comment in comments %}
            <div style="display: flex;" >

                <div style="display: flex; margin-top: 8px;" >
                    <p>{{ comment.user }}</p> 
                    <p style="margin-left: 5px; margin-right: 5px;">{{ comment.content }}</p></div> 
                <!--delete-->
                {% if user == comment.user %}
                <form action="{% url 'photos:comments_delete' photo.pk comment.pk %}" method="POST" class="d-inline">
                    {% csrf_token %}
                    <input class="btn btn-outline-danger" style="width: 80px;"  type="submit" value="DELETE">
                </form>
                {% endif %}
            </div>
            
        {% empty %}
            <p>댓글이 없어요..</p>
        {% endfor %}
        </ul>

        <hr>


    <div>
      <form action="{% url 'photos:likes' photo.pk %}" method='POST'>
        {% csrf_token %}
        {% if user in photo.like_users.all %}
            <div style="display: flex; align-items: center; justify-content: space-between;">
                <input type="submit" value='좋아요 취소'>
                <p>{{photo.like_users.count}} likes </p>
            </div>
        {% else %}
            <div style="display: flex; align-items: center; justify-content: space-between;">
                <input type="submit" value='좋아요'>
                <p>{{photo.like_users.count}} likes </p>
            </div>
        {% endif %}
      </form>
    </div>

        <!--create-->
        {% if request.user.is_authenticated %}
        <form action="{% url 'photos:comments_create' photo.id %}" method="POST">
            {% csrf_token %}
            {{ comment_form }}
            <input class="btn btn-outline-primary" style="margin-left: 720px;" type="submit" value="확인">
        </form>
        {% else %}
        <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인하세요.]</a>
        {% endif %}

    

    </div>
    
    
{% endblock %}

portfolio/pjt/templates/photos/display_image.html
{% extends 'base.html' %}
{% block style %}
    

{% endblock %}
{% block content %}
<h1 style="margin-top:100px;">새로 업로드 된 사진</h1>
<div style="display: flex; width: 1600px; margin: 0 auto; margin-top: 20px;">   
    <button onclick="RightNew()" style="height: 50px; width: 50px; margin: 20px; margin-top: 120px;" >◀</button>
    <div id="new-image-display" style="height: 250px; width: 1500px; margin-top: 30px;  overflow: auto;  white-space: nowrap; margin-left: auto; margin-right: auto;" >
        {% for i in images %}      
        <img src="{{ i.imgfile.url }}" alt="" style="height: 200px; margin: 5px">
        {% endfor %}
    </div>
    <button onclick="LeftNew()" style="height: 50px; width: 50px; margin: 20px; margin-top: 120px;" >▶</button>
</div>

<h1 style="margin-top:100px;">인기 사진</h1>
<div style="display: flex; width: 1600px; margin: 0 auto; margin-top: 20px;">   
    <button onclick="RightHot()" style="height: 50px; width: 50px; margin: 20px; margin-top: 120px;" >◀</button>
    <div id="hot-image-display" style="height: 250px; width: 1500px; margin-top: 30px;  overflow: auto;  white-space: nowrap; margin-left: auto; margin-right: auto;" >
        {% for i in images %}      
        <img src="{{ i.imgfile.url }}" alt="" style="height: 200px; margin: 5px">
        {% endfor %}
    </div>
    <button onclick="LeftHot()" style="height: 50px; width: 50px; margin: 20px; margin-top: 120px;" >▶</button>
</div>
<style>
    #new-image-display{
        -ms-overflow-style: none;
    }
    #new-image-display::-webkit-scrollbar{
    display:none;
    }
    #hot-image-display{
        -ms-overflow-style: none;
    }
    #hot-image-display::-webkit-scrollbar{
    display:none;
    }
</style>
<script>

    let Newpos = 0;

    function LeftNew(){
        Newpos = Newpos+100;
        //alert(pos);
        $( '#new-image-display' ).scrollLeft( Newpos );
    }
    
    function RightNew(){
        Newpos = Newpos-100;
        if(Newpos<0)
        Newpos = 0;
        //alert(pos);
        $( '#new-image-display' ).scrollLeft( Newpos );
    }
    
    let Hotpos = 0;

    function LeftHot(){
        Hotpos = Hotpos+100;
        //alert(pos);
        $( '#hot-image-display' ).scrollLeft( Hotpos );
    }
    
    function RightHot(){
        Hotpos = Hotpos-100;
        if(Hotpos<0)
            Hotpos = 0;
        //alert(pos);
        $( '#hot-image-display' ).scrollLeft( Hotpos );
    }
    
 </script> 
{% endblock %}

portfolio/pjt/templates/photos/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="border">
    <div class="button-container" style="margin-top: 70px;">
        <button type="button" class="btn btn-outline-primary" style="cursor:pointer; margin-left: 1700px; width:80px; height:40px; " OnClick="location.href='/PhotoUpload'">업로드</button>   
    </div>



        <h1 style="margin-top:50px;">새로 업로드 된 사진</h1> 
        <div style="display: flex; width: 1600px; margin: 0 auto; margin-top: 20px;">   
            <button onclick="RightNew()" style="height: 50px; width: 50px; margin: 20px; margin-top: 120px;" >◀</button>
            <div id="new-image-display" style="height: 250px; width: 1500px; margin-top: 30px;  overflow: auto;  white-space: nowrap; margin-left: auto; margin-right: auto;" >
                {% for i in images %}      
                <a href="{% url 'photos:detail' i.id %}"><img src="{{ i.imgfile.url }}" alt="" style="height: 200px; margin: 5px"></a>
                {% endfor %}
            </div>
            <button onclick="LeftNew()" style="height: 50px; width: 50px; margin: 20px; margin-top: 120px;" >▶</button>
        </div>

        <h1 style="margin-top:100px;">인기 사진</h1>
        <div style="display: flex; width: 1600px; margin: 0 auto; margin-top: 20px;">   
            <button onclick="RightHot()" style="height: 50px; width: 50px; margin: 20px; margin-top: 120px;" >◀</button>
            <div id="hot-image-display" style="height: 250px; width: 1500px; margin-top: 30px;  overflow: auto;  white-space: nowrap; margin-left: auto; margin-right: auto;" >
                {% for i in ordered_images %}      
                <a href="{% url 'photos:detail' i.id %}"><img src="{{ i.imgfile.url }}" alt="" style="height: 200px; margin: 5px"></a>
                {% endfor %}
            </div>
            <button onclick="LeftHot()" style="height: 50px; width: 50px; margin: 20px; margin-top: 120px;" >▶</button>
        </div>

</div>

 

<style>
    #new-image-display{
        -ms-overflow-style: none;
    }
    #new-image-display::-webkit-scrollbar{
    display:none;
    }
    #hot-image-display{
        -ms-overflow-style: none;
    }
    #hot-image-display::-webkit-scrollbar{
    display:none;
    }
</style>
<script>

    let Newpos = 0;

    function LeftNew(){
        Newpos = Newpos+100;
        //alert(pos);
        $( '#new-image-display' ).scrollLeft( Newpos );
    }
    
    function RightNew(){
        Newpos = Newpos-100;
        if(Newpos<0)
        Newpos = 0;
        //alert(pos);
        $( '#new-image-display' ).scrollLeft( Newpos );
    }
    
    let Hotpos = 0;

    function LeftHot(){
        Hotpos = Hotpos+100;
        //alert(pos);
        $( '#hot-image-display' ).scrollLeft( Hotpos );
    }
    
    function RightHot(){
        Hotpos = Hotpos-100;
        if(Hotpos<0)
            Hotpos = 0;
        //alert(pos);
        $( '#hot-image-display' ).scrollLeft( Hotpos );
    }
    
 </script> 




{% endblock %}

portfolio/pjt/templates/photos/second_index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="border">
    <h1 style="margin-top:100px;">새로 업로드 된 사진</h1>
<div style="display: flex; width: 1600px; margin: 0 auto; margin-top: 20px;">   
    <button onclick="RightNew()" style="height: 50px; width: 50px; margin: 20px; margin-top: 120px;" >◀</button>
    <div id="new-image-display" style="height: 250px; width: 1500px; margin-top: 30px;  overflow: auto;  white-space: nowrap; margin-left: auto; margin-right: auto;" >
        {% for i in images %}      
        <a href="{% url 'acconts:index' %}"><img src="{{ i.imgfile.url }}" alt="" style="height: 200px; margin: 5px"></a>
        {% endfor %}
    </div>
    <button onclick="LeftNew()" style="height: 50px; width: 50px; margin: 20px; margin-top: 120px;" >▶</button>
</div>

<h1 style="margin-top:100px;">인기 사진</h1>
<div style="display: flex; width: 1600px; margin: 0 auto; margin-top: 20px;">   
    <button onclick="RightHot()" style="height: 50px; width: 50px; margin: 20px; margin-top: 120px;" >◀</button>
    <div id="hot-image-display" style="height: 250px; width: 1500px; margin-top: 30px;  overflow: auto;  white-space: nowrap; margin-left: auto; margin-right: auto;" >
        {% for i in images %}      
        <a href="{% url 'acconts:index' %}"><img src="{{ i.imgfile.url }}" alt="" style="height: 200px; margin: 5px"></a>
        {% endfor %}
    </div>
    <button onclick="LeftHot()" style="height: 50px; width: 50px; margin: 20px; margin-top: 120px;" >▶</button>
</div>
 

<style>
    #new-image-display{
        -ms-overflow-style: none;
    }
    #new-image-display::-webkit-scrollbar{
    display:none;
    }
    #hot-image-display{
        -ms-overflow-style: none;
    }
    #hot-image-display::-webkit-scrollbar{
    display:none;
    }
</style>
<script>

    let Newpos = 0;

    function LeftNew(){
        Newpos = Newpos+100;
        //alert(pos);
        $( '#new-image-display' ).scrollLeft( Newpos );
    }
    
    function RightNew(){
        Newpos = Newpos-100;
        if(Newpos<0)
        Newpos = 0;
        //alert(pos);
        $( '#new-image-display' ).scrollLeft( Newpos );
    }
    
    let Hotpos = 0;

    function LeftHot(){
        Hotpos = Hotpos+100;
        //alert(pos);
        $( '#hot-image-display' ).scrollLeft( Hotpos );
    }
    
    function RightHot(){
        Hotpos = Hotpos-100;
        if(Hotpos<0)
            Hotpos = 0;
        //alert(pos);
        $( '#hot-image-display' ).scrollLeft( Hotpos );
    }
    
 </script> 



</div>
{% endblock %}